name: Generate Package Manifest

on:
  workflow_call:
    inputs:
      tag:
        description: 'The tag to use'
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      LNB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to use'
        required: true
        type: string

jobs:
  run-package-manifest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ebelfarsi/package-manifest:latest

      - name: Run Docker Container
        run: docker run --name package-container -e REPO_OWNER=hpcc-systems -e REPO_NAME=HPCC-Platform -e TAG=community_9.8.2-1 -e GIT_TKN=${{ secrets.LNB_TOKEN }} ebelfarsi/package-manifest:latest

      - name: Fetch Output from Container
        run: docker cp package-container:/app/output.json ${{ github.workspace }}/output.json

      - name: Prepare Directory Structure
        run: |
          version=$(jq -r '.[0].Version' ${{ github.workspace }}/output.json | cut -d'-' -f1)
          base_dir="${{ github.workspace }}/CE-Candidate-${version}"
          mkdir -p "$base_dir"
          jq -r '.[] | .Edge_Cast_path' ${{ github.workspace }}/output.json | while read path; do
            full_path="$base_dir/$(echo $path | sed 's#releases/CE-Candidate-[^/]*##')"
            mkdir -p "$(dirname "$full_path")"
            touch "$full_path"
          done

      - name: Sync Directory to S3 Bucket
        shell: bash
        run: |
          version=$(jq -r '.[0].Version' ${{ github.workspace }}/output.json | cut -d'-' -f1)
          base_dir="${{ github.workspace }}/CE-Candidate-${version}"
          aws s3 sync "$base_dir" s3://ebelfarsi-bucket/
        


      - name: Upload output.json to GitHub Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          generateReleaseNotes: false
          prerelease: ${{ contains(github.ref, '-rc') }}
          artifacts: ${{ github.workspace }}/bin/output.json
          token: ${{ secrets.LNB_TOKEN }}
