name: Generate Package Manifest

on:
  workflow_call:
    inputs:
      tag:
        description: 'The tag to use'
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      LNB_TOKEN:
        required: true

jobs:
  run-package-manifest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ebelfarsi/package-manifest:latest

      - name: Run Docker Container
        run: docker run --name package-container -e REPO_OWNER=${{ github.repository_owner }} -e REPO_NAME=HPCC-Platform -e TAG=${{ inputs.tag }} -e GIT_TKN=${{ secrets.LNB_TOKEN }} ebelfarsi/package-manifest:latest

      - name: Fetch Output from Container
        run: docker cp package-container:/app/output.json ${{ github.workspace }}/output.json

      - name: Upload output.json to GitHub Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          generateReleaseNotes: false
          prerelease: ${{ contains(github.ref, '-rc') }}
          artifacts: ${{ github.workspace }}/output.json
          token: ${{ secrets.LNB_TOKEN }}
